### PR TITLE
Fix for TypeError in its_all_about_you example

### LINKED ISSUE #3654: TypeError in example
### Page URL

https://dart.dev/tutorials/web/fetch-data

### Page source

_No response_

### Describe the problem

I see the following error while running its_all_about_you app:
Uncaught Error: TypeError: Instance of 'JSArray<dynamic>': type 'JSArray<dynamic>' is not a subtype of type 'List<String>'

### Expected fix

Edit the example code to cast correctly.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kshiitiz**
Closes #3654

### CODE REVIEW

File: examples/fetch_data/web/main.dart [hunk 1]
```diff
@@ -76,7 +76,7 @@ void _populateFromJson() {
   favoriteNumber.value = jsonData['favoriteNumber'].toString();
   valueOfPi.value = jsonData['valueOfPi'].toString();
   horoscope.value = jsonData['horoscope'].toString();
-  final favoriteThings = jsonData['favoriteThings'] as List<String>;
+  final favoriteThings = jsonData['favoriteThings'] as List;
```
Comment (parlough) [inline examples/fetch_data/web/main.dart:79]:
```suggestion
  final favoriteThings = List<String>.from(jsonData['favoriteThings'] as List);
```

File: src/_tutorials/web/fetch-data.md [hunk 2]
```diff
@@ -135,7 +135,7 @@ void _populateFromJson() {
   favoriteNumber.value = jsonData['favoriteNumber'].toString();
   valueOfPi.value = jsonData['valueOfPi'].toString();
   horoscope.value = jsonData['horoscope'].toString();
-  final favoriteThings = jsonData['favoriteThings'] as List<String>;
+  final favoriteThings = jsonData['favoriteThings'] as List;
```
Comment (parlough) [inline src/_tutorials/web/fetch-data.md:138]:
```suggestion
  final favoriteThings = List<String>.from(jsonData['favoriteThings'] as List);
```

**Review by parlough — APPROVED** [review]
Thanks again! Two minor changes which I should be able to commit myself.
