### PR TITLE
Trigger popovers on click, and fix scrolling even in subviews

### LINKED ISSUE #530: Popovers should trigger on click, and follow their base elt when scrolled
- On the front page, popovers associated with the code sample don't stay attached to their base element when the code is scrolled.
- @anders-sandholm pointed out in https://github.com/dart-lang/site-www/issues/6#issuecomment-359613292 that we need the popovers to trigger on click events only (not on hover), if we eventually want to be able to click links inside the popover.

In restoring click handlers, ensure that opening one popover closes all other open popovers.

### PR DESCRIPTION
**Pull request by chalin**
Fixes #530

As explained in `main.js`, popovers inside the front page sample code block open downwards so that it is always possible to scroll the full popover content into view.

Staged at:
- https://dartlang-org-staging-0.firebaseapp.com
- https://dartlang-org-staging-0.firebaseapp.com/tutorials/libraries/shared-pkgs
- https://dartlang-org-staging-0.firebaseapp.com/tutorials/dart-vm/cmdline

Tested in Chrome, Firefox and Safari.

Continued prep work for #6.

---

Here are examples of front page code example popovers:

screen shot 2018-01-22 at 22 19 38

screen shot 2018-01-22 at 22 46 37

And one from the prose:

screen shot 2018-01-22 at 22 46 51

### CODE REVIEW

File: src/_assets/javascripts/main.js [hunk 1]
```diff
@@ -88,12 +88,44 @@ $(document).on('ready', function(){
...
+        viewport === 'body' ? 'top' : 'bottom',
+      trigger: 'click', // focus doesn't toggle for non-anchor elements
+      viewport: viewport,
+    }).on('shown.bs.popover', function () {
+      // _After_ this popover has been shown, add 'popover-open' class.
+      $(this).addClass(openPopClass);
+    });
+  }
+
+  // Frontpage popovers insdie the #code-sample, should scroll with the enclosing <pre>.
```
Comment (kwalrath) [inline src/_assets/javascripts/main.js]: insdie -> inside
, should -> should

(just to prove I looked :)

File: src/_assets/javascripts/main.js [hunk 2]
```diff
@@ -88,12 +88,44 @@ $(document).on('ready', function(){
...
+  setPopovers($('body.homepage #code-sample'), 'pre');
+  // All other popovers should scoll with the page.
```
Comment (kwalrath) [inline src/_assets/javascripts/main.js]: scoll -> scroll

**Comment by chalin** [comment]
Typos fixed!
