### PR TITLE
Fix a number of "Effective Dart" issues.

### LINKED ISSUE #995: Remove note about whereType status
See https://github.com/dart-lang/site-www/pull/991#pullrequestreview-136003640 and https://github.com/dart-lang/sdk/issues/32463 for details.

/cc @munificent @lrhn @Hixie

### PR DESCRIPTION
**Pull request by munificent**
Tijo notes a bunch of good stuff:

- Some examples used "=>" for void members even though a guideline
  tells you not to do that.

- A typedef for a generic should have been a generic typedef.

- The background color for neutral code snippets is too similar to the
  bad background color for colorblind people. I somewhat mitigated this
  by turning a couple of the neutral examples into explicit good and bad
  ones.

  It's worth tweaking the neutral background color to be more distinct
  from the red background for red-green colorblindness, but I didn't
  feel comfortable making visual changes to the site.

cc @tijoforyou

---

Fixes #995

### CODE REVIEW

**Comment by chalin** [comment]
Good to go once Travis is happy.

The build is currently failing because of:

```
lint • Type annotate public APIs at test/effective_dart_test.dart:28:7 • type_annotate_public_apis
```

File: examples/misc/test/effective_dart_test.dart [hunk 1]
```diff
@@ -25,20 +25,29 @@ void main() {
     });
 
     test('runtimeType', () {
-      _test() {
-        // #docregion list-from-2
+      good() {
```
Comment (chalin) [inline examples/misc/test/effective_dart_test.dart]: The linter will probably be more happy with: good() -> _good()

File: examples/misc/test/effective_dart_test.dart [hunk 2]
```diff
@@ -25,20 +25,29 @@ void main() {
...
         var iterable = [1, 2, 3];
 
         // Prints "List<int>":
         print(iterable.toList().runtimeType);
+        // #enddocregion list-from-good
+      }
+
+      expect(good, prints('List<int>\n'));
+
+      bad() {
```
Comment (chalin) [inline examples/misc/test/effective_dart_test.dart]: Ditto: bad() -> _bad()

(with the corresponding fix in the expect())

**Comment by chalin** [comment]
@munificent - I can make the changes if you'd like.

File: examples/misc/test/effective_dart_test.dart (hunk 2 above)
Comment (munificent) [reply examples/misc/test/effective_dart_test.dart]: Ugh, that lint is dumb. Local functions are never part of APIs.

Changed them to be lambdas.

Comment (chalin) [reply examples/misc/test/effective_dart_test.dart]: Yeah, I didn't open an issue the last time I faced this, but I have now so that it can get fixed! :) https://github.com/dart-lang/linter/issues/1108
