### PR TITLE
fix: make heading anchors copy full URL to clipboard fixes #6756

### LINKED ISSUE #6756: [user experience] Copy anchor link to clipboard in clicking header
### Describe the problem

Steps to reproduce:

1. browse to https://dart.dev/tools/pub/packages
2. scroll down to "Upgrading a dependency"
3. click "#" behind "Upgrading a dependency"
4. Go to a different tab with a text field
5. Hit ctrl+v.

Expected behavior

* Pastes in https://dart.dev/tools/pub/packages#upgrading-a-dependency

Actual behavior

* Pastes in whatever you had on your clipboard, not the link of the anchor on the website.

### PR DESCRIPTION
**Pull request by Anushreebasics**
### Summary
This PR fixes issue #6756 where clicking the '#' anchor next to headings
did not copy the section link to the clipboard.  

### Changes
- Updated `HeaderWrapperExtension` to add an inline `onclick` handler
  for the heading anchor `<a>` elements.
- Clicking '#' now:
  - Copies the full URL including fragment to the clipboard
  - Updates the URL in the address bar
  - Prevents default page jump behavior
  - Temporarily replaces '#' with a smaller 'Copied!' text for 1.2 seconds to provide visual feedback

### Testing
- Verified that clicking '#' on h2–h5 headings copies the correct URL
- Confirmed that the page URL updates without scrolling
- Works across multiple headings on the same page

### Notes
- This approach adds behavior directly in the anchor element.
- Alternative approach would be a global client-side handler, but this
  is safe and consistent with current Jaspr HTML generation.

Fixes #6756 

reference video: 

https://github.com/user-attachments/assets/06411e8d-07c2-4057-a20e-ace125897a16

### CODE REVIEW

File: site/lib/src/extensions/header_processor.dart [hunk 1]
```diff
@@ -50,6 +50,18 @@ final class HeaderWrapperExtension implements PageExtension {
             'class': 'heading-link',
             'href': '#$headerId',
             'aria-label': "Link to '$headerText' section",
+            // 👇 COPY TO CLIPBOARD LOGIC
+            'onclick': '''
```
Comment (parlough) [inline site/lib/src/extensions/header_processor.dart]: Implementing this as an inline JS string is quite repetitive in the output HTML, harder to maintain, and causes us to lose out on static checks.

Perhaps a more robust approach would be to add a new Dart function to https://github.com/dart-lang/site-www/blob/main/site/lib/src/client/global_scripts.dart that finds the relevant anchors and adds the behaviors to them?

Another option would be a hydrated Jaspr client component, but I think the single global handler should be sufficient for this case.

**Review by parlough — CHANGES_REQUESTED** [review]
Thanks for the PR, I appreciate it! However I have some concerns about the inline-JS approach.

Could you migrate it to a setup function written in Dart? Or a Jaspr client component if you prefer that? Let me know if you have any concerns or hit any issues though. Thanks again!

**Comment by Anushreebasics** [comment]
@parlough please review the changes:

Moved the heading anchor click behavior from inline JavaScript to a single global handler in global_scripts.dart.
This avoids duplicated JS in the generated HTML, improves maintainability, and keeps content generation separate from client-side behavior. The new handler copies the section URL to the clipboard, updates the hash without jumping, and shows brief visual feedback.

File: site/lib/src/client/global_scripts.dart [hunk 2]
```diff
@@ -24,6 +25,46 @@ void setUpSite() {
...
+    anchor.addEventListener(
+      'click',
+      ((web.Event event) {
+        event.preventDefault();
+
+        final headingId = anchor.dataset['headingId'];
+        if (headingId == null || headingId.isEmpty) return;
+
+        final url =
+            '${web.window.location.origin}${web.window.location.pathname}#$headingId';
```
Comment (parlough) [inline site/lib/src/client/global_scripts.dart]: To make this a bit safer and also easier to read, we could use the `Uri` class provided by Dart:


```suggestion
        final url = Uri.parse(web.window.location.href)
            .replace(fragment: headingId)
            .toString();
```

File: site/lib/src/client/global_scripts.dart [hunk 3]
```diff
@@ -24,6 +25,46 @@ void setUpSite() {
...
+  for (var i = 0; i < anchors.length; i++) {
+    final anchor = anchors.item(i) as web.HTMLAnchorElement;
+
+    anchor.addEventListener(
+      'click',
+      ((web.Event event) {
+        event.preventDefault();
+
+        final headingId = anchor.dataset['headingId'];
+        if (headingId == null || headingId.isEmpty) return;
```
Comment (parlough) [inline site/lib/src/client/global_scripts.dart]: Rather than adding a new data entry, would it make sense to just reuse the `href` already present on the anchor?

File: site/lib/src/client/global_scripts.dart [hunk 4]
```diff
@@ -24,6 +25,46 @@ void setUpSite() {
...
+
+        // Temporary visual feedback
+        final originalText = anchor.textContent;
+        anchor.textContent = 'Copied!';
+        web.window.setTimeout(
+          (() {
+            anchor.textContent = originalText;
+          }).toJS,
+          1200 as JSAny,
+        );
```
Comment (parlough) [inline site/lib/src/client/global_scripts.dart]: Rather than using `setTimeout` which is a bit awkward through Dart, we can instead use `Future.delayed` which is built in :D 


```suggestion
        Future<void>.delayed(const Duration(milliseconds: 1200), () {
          anchor.textContent = originalText;
        });
```

**Comment by Anushreebasics** [comment]
@parlough please review the changes

**Comment by Anushreebasics** [comment]
@antfitch  @conooi, please review this PR

**Comment by Anushreebasics** [comment]
@parlough please review this PR

**Comment by conooi** [comment]
Hi @Anushreebasics! Thanks for all your help. Adding in @khanhnwin to review your code.

**Comment by Anushreebasics** [comment]
@khanhnwin please review

**Comment by khanhnwin** [comment]
This looks great, thanks @Anushreebasics!

**Comment by Anushreebasics** [comment]
@conooi the branch is up to date with the main branch and squashed them to one commit, kindly review

**Comment by Anushreebasics** [comment]
@conooi please review, I have fixed the formatting errors

**Comment by conooi** [comment]
@parlough please review when you have time :)

**Comment by Anushreebasics** [comment]
@parlough please review

**Review by parlough — APPROVED** [review]
Sorry about the delay in reviewing this again!

Looks good to me. I did push a small change adding a fallback behavior incase the clipboard access failed.

Thanks so much @Anushreebasics!
